In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0], [5,5,0]], columns=['cgpa','profile_score', 'placed'])

In [ ]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [ ]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1, L):
        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
    return parameters

In [ ]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [ ]:
def linear_forward(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b
    A = sigmoid(Z)
    return A

In [ ]:
def L_layer_forward(X, parameters):
    A = X
    L = len(parameters) // 2
    for l in range(1, L+1):
        A_prev = A
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        A = linear_forward(A_prev, Wl, bl)
    return A, A_prev

In [ ]:
def update_parameters(parameters, y, y_hat, A1, X):
     parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
     parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
     parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

     parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
     parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
     parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

     parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
     parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
     parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [ ]:

X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['placed']].values[0][0]
Parameters = initialize_parameters([2,2,1])
y_hat, A1 = L_layer_forward(X, Parameters)
y_hat=y_hat[0][0]
update_parameters(Parameters, y, y_hat, A1, X)
print('Loss for this student - ', -y*np.log(y_hat)-(1-y)*np.log(1-y_hat))
Parameters


Loss for this student -  0.613402628898913


{'W1': array([[0.10073919, 0.10073919],
        [0.10073919, 0.10073919]]),
 'b1': array([[9.23985814e-05],
        [9.23985814e-05]]),
 'W2': array([[0.10076295],
        [0.10076295]]),
 'b2': array([[0.10167994]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1)
y = df[['placed']].values[1][0]

y_hat, A1 = L_layer_forward(X, Parameters)
y_hat=y_hat[0][0]
update_parameters(Parameters, y, y_hat, A1, X)
print('Loss for this student - ', -y*np.log(y_hat)-(1-y)*np.log(1-y_hat))
Parameters

Loss for this student -  0.5673673895732062


{'W1': array([[0.10135437, 0.10153013],
        [0.10135437, 0.10153013]]),
 'b1': array([[0.00018028],
        [0.00018028]]),
 'W2': array([[0.10148489],
        [0.10148489]]),
 'b2': array([[0.10235086]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1)
y = df[['placed']].values[2][0]

y_hat, A1 = L_layer_forward(X, Parameters)
y_hat=y_hat[0][0]
update_parameters(Parameters, y, y_hat, A1, X)
print('Loss for this student - ', -y*np.log(y_hat)-(1-y)*np.log(1-y_hat))
Parameters

Loss for this student -  0.8382987453162329


{'W1': array([[0.10066964, 0.10038893],
        [0.10066965, 0.10038893]]),
 'b1': array([[6.61607529e-05],
        [6.61612515e-05]]),
 'W2': array([[0.10053702],
        [0.10053658]]),
 'b2': array([[0.09940147]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1)
y = df[['placed']].values[3][0]

y_hat, A1 = L_layer_forward(X, Parameters)
y_hat=y_hat[0][0]
update_parameters(Parameters, y, y_hat, A1, X)
print('Loss for this student - ', -y*np.log(y_hat)-(1-y)*np.log(1-y_hat))
Parameters

Loss for this student -  0.8240348467352431


{'W1': array([[0.1001099 , 0.09982919],
        [0.10010991, 0.09982919]]),
 'b1': array([[-4.57874025e-05],
        [-4.57871046e-05]]),
 'W2': array([[0.09971478],
        [0.09971496]]),
 'b2': array([[0.09859227]])}

In [ ]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['placed']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.7107759026308988
Epoch -  2 Loss -  0.6996871677848441
Epoch -  3 Loss -  0.6996384275321997
Epoch -  4 Loss -  0.6995901433478264
Epoch -  5 Loss -  0.699542309987999
Epoch -  6 Loss -  0.6994949222833107
Epoch -  7 Loss -  0.699447975137458
Epoch -  8 Loss -  0.699401463526046
Epoch -  9 Loss -  0.699355382495416
Epoch -  10 Loss -  0.6993097271614912
Epoch -  11 Loss -  0.699264492708646
Epoch -  12 Loss -  0.6992196743885906
Epoch -  13 Loss -  0.6991752675192797
Epoch -  14 Loss -  0.6991312674838359
Epoch -  15 Loss -  0.6990876697294947
Epoch -  16 Loss -  0.6990444697665664
Epoch -  17 Loss -  0.6990016631674176
Epoch -  18 Loss -  0.6989592455654681
Epoch -  19 Loss -  0.6989172126542077
Epoch -  20 Loss -  0.6988755601862281
Epoch -  21 Loss -  0.6988342839722739
Epoch -  22 Loss -  0.6987933798803072
Epoch -  23 Loss -  0.6987528438345912
Epoch -  24 Loss -  0.6987126718147884
Epoch -  25 Loss -  0.6986728598550741
Epoch -  26 Loss -  0.6986334040432669


{'W1': array([[0.10450357, 0.09178778],
        [0.10449706, 0.09177002]]),
 'b1': array([[-0.00215842],
        [-0.00216175]]),
 'W2': array([[0.08527977],
        [0.08551955]]),
 'b2': array([[0.08441461]])}

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2, activation='sigmoid', input_dim = 2))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[ 0.14261341, -0.6081431 ],
        [-0.6109095 , -0.706574  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.5254252],
        [1.3509663]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1, 0.1],
        [0.1, 0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizers=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizers)

In [ ]:
model.fit(df.iloc[:,0:-1].values, df['placed'].values, epochs=50,verbose=1, batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.6843
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7069 
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7306 
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6838 
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7064 
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6838 
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6838 
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7294 
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6839 
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7160 
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6575 
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6839 
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7307 
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7281 
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6744 
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━━